title: Codex Academia
theme: just-the-docs

just_the_docs:
  nav_order: 1
  search_enabled: true
  aux_links: {}
  # Defines sidebar hierarchy with collapsible menus
  collections:
    docs:
      output: true

